### ISSUE TITLE
print_fibonacci() Feels Difficult

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/phase-3-sequences#8]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195260?module_item_id=439018

### Concern

The `print_fibonacci()` assignment feels a little complicated for students. Could just be me!

**Comment by professor-ben** [comment]
I refactored this a bit- you should see it reflected in the repo, along with a new solution branch. It's definitely a bit more challenging than the lab exercises up to that point, since it requires a synthesis of conditionals, loops, lists, and (ideally) ranges- but this is also a very common interview question for entry-level Python jobs.

More than happy to refactor this or provide more scaffolding if it's still needed- y'all know the students better than me!

-Ben
